function marked = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   MARKED = IMPORTFILE(FILENAME) Reads data from text file FILENAME for
%   the default selection.
%
%   MARKED = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows
%   STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   marked = importfile('marked.csv', 1, 9552);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2018/03/24 17:25:49

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as text:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric text to numbers.
% Replace non-numeric text with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = mat2cell(dataArray{col}, ones(length(dataArray{col}), 1));
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,10,11,12,15]
    % Converts text in the input cell array to numbers. Replaced non-numeric
    % text with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1)
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData(row), regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if numbers.contains(',')
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(numbers, thousandsRegExp, 'once'))
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric text to numbers.
            if ~invalidThousandsSeparator
                numbers = textscan(char(strrep(numbers, ',', '')), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch
            raw{row, col} = rawData{row};
        end
    end
end

% Convert the contents of columns with dates to MATLAB datetimes using the
% specified date format.
try
    dates{14} = datetime(dataArray{14}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
catch
    try
        % Handle dates surrounded by quotes
        dataArray{14} = cellfun(@(x) x(2:end-1), dataArray{14}, 'UniformOutput', false);
        dates{14} = datetime(dataArray{14}, 'Format', 'HH:mm:ss', 'InputFormat', 'HH:mm:ss');
    catch
        dates{14} = repmat(datetime([NaN NaN NaN]), size(dataArray{14}));
    end
end

dates = dates(:,14);

%% Split data into numeric and string columns.
rawNumericColumns = raw(:, [1,2,3,4,5,10,11,12,15]);
rawStringColumns = string(raw(:, [6,7,8,9,13,16,17]));


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Make sure any text containing <undefined> is properly converted to an <undefined> categorical
for catIdx = [1,3,4,5]
    idx = (rawStringColumns(:, catIdx) == "<undefined>");
    rawStringColumns(idx, catIdx) = "";
end

%% Create output variable
marked = table;
marked.ID = cell2mat(rawNumericColumns(:, 1));
marked.user_id = cell2mat(rawNumericColumns(:, 2));
marked.type = cell2mat(rawNumericColumns(:, 3));
marked.Sentimentlabel = cell2mat(rawNumericColumns(:, 4));
marked.labelsvalue = cell2mat(rawNumericColumns(:, 5));
marked.usernameTweet = categorical(rawStringColumns(:, 1));
marked.text = rawStringColumns(:, 2);
marked.is_reply = categorical(rawStringColumns(:, 3));
marked.is_retweet = categorical(rawStringColumns(:, 4));
marked.nbr_favorite = cell2mat(rawNumericColumns(:, 6));
marked.nbr_reply = cell2mat(rawNumericColumns(:, 7));
marked.nbr_retweet = cell2mat(rawNumericColumns(:, 8));
marked.date = categorical(rawStringColumns(:, 5));
marked.time = dates{:, 1};
marked.has_media = cell2mat(rawNumericColumns(:, 9));
marked.medias0 = rawStringColumns(:, 6);
marked.url = rawStringColumns(:, 7);

% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% marked.time=datenum(marked.time);

